apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: timeline-deployment
  namespace: lei-gcp
  labels:
    app: timeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeline
  template:
    metadata:
      labels:
        app: timeline
    spec:
      containers:
      - name: timeline
        image: gcr.io/xmatters-eng-dev/timeline:0.8
        ports:
        - containerPort: 80
